In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    "a" : ['one', 'two'] * 3,
    "b" : [1,1,2,3,2,3]
})

df

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [4]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [5]:
df.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [7]:
df["c"] = range(6)
df

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [8]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [9]:
df.duplicated(['a', 'b'], keep='last')

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [10]:
df = pd.DataFrame({
    "names" : ["Niall", "Louis", "Liam", "Harry", "Zayn"],
    "scores" : [100, 99, 81, 89, 91]
})

df

names  scores
0  Niall     100
1  Louis      99
2   Liam      81
3  Harry      89
4   Zayn      91

In [11]:
classes = {"Niall" : "A", "Louis" : "B", "Liam" : "C", "Harry" : "B", "Zayn" : "A"}

In [13]:
n = df.names.str.capitalize()
n

0    Niall
1    Louis
2     Liam
3    Harry
4     Zayn
Name: names, dtype: object

In [14]:
df['branches'] = n.map(classes)
df

names  scores branches
0  Niall     100        A
1  Louis      99        B
2   Liam      81        C
3  Harry      89        B
4   Zayn      91        A

In [15]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [17]:
s.replace(70, np.nan)


0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [19]:
s

0    80
1    70
2    90
3    60
dtype: int64

In [18]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [20]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [21]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [22]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [23]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [25]:
df.rename(index=str.title, columns=str.capitalize)

Tim  Tom  Kim  Sam
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [28]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [31]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
)
df

tim  tom  kim  sam
Ten      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [32]:
df

tim  tom  kim  sam
Ten      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [33]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]

In [34]:
x=[20,40,60,80,100]

x = [20, 40, 60, 80, 100] defines 4 bins:

(20, 40]: Values > 20 and ≤ 40

(40, 60]: Values > 40 and ≤ 60

(60, 80]: Values > 60 and ≤ 80

(80, 100]: Values > 80 and ≤ 100

Therefore

30 → (20, 40]	 (30 lies in this range)

80 → (60, 80]

40 → (20, 40] (but 40 is on the left boundary, so it moves to (40, 60])	

90 → (80, 100]	

60 → (40, 60]

In [ ]:
y = pd.cut(sc, x)
y



[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [36]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [37]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [40]:
pd.value_counts(y)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23044\3605348509.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(y)


(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [44]:
pd.value_counts(y)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23044\3605348509.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(y)


(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [45]:
sc = [30,80,40,90,60,45,95,75,55,100,65,85]

This can be used for marking scheme when you want to assign a grade based on marks range

In [46]:
x = [0, 33, 60, 85, 100]

In [52]:
y = pd.cut(sc, x, labels=["Fail", "Good", "Very Good", "Excellent"])
y

['Fail', 'Very Good', 'Good', 'Excellent', 'Good', ..., 'Very Good', 'Good', 'Excellent', 'Very Good', 'Very Good']
Length: 12
Categories (4, object): ['Fail' < 'Good' < 'Very Good' < 'Excellent']

In [48]:
y.codes

array([0, 2, 1, 3, 1, 1, 3, 2, 1, 3, 2, 2], dtype=int8)

In [51]:
y.categories

IntervalIndex([(0, 33], (33, 60], (60, 85], (85, 100]], dtype='interval[int64, right]')

In [55]:
y = pd.cut(sc,10)
y

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [62]:
y.categories

IntervalIndex([(29.93, 37.0],  (37.0, 44.0],  (44.0, 51.0],  (51.0, 58.0],
                (58.0, 65.0],  (65.0, 72.0],  (72.0, 79.0],  (79.0, 86.0],
                (86.0, 93.0], (93.0, 100.0]],
              dtype='interval[float64, right]')

In [66]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [68]:
data.shape

(1000, 4)

In [69]:
data.head()

0         1         2         3
0 -1.765558 -0.322184 -0.130323 -0.636168
1  0.336728  2.887557 -0.067640  0.769932
2  1.336276 -0.235238  1.551201  0.037672
3  1.372909  0.564882  1.463869  0.489174
4 -0.160002 -0.519747  0.853309 -1.376392

In [71]:
col = data[0]

In [72]:
col[np.abs(col) > 3]

625   -3.003154
853   -3.001045
919   -3.180106
Name: 0, dtype: float64

In [74]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0 -1.0  1.0
2  1.0 -1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4 -1.0 -1.0  1.0 -1.0

In [75]:
data = pd.DataFrame(np.arange(12).reshape(4,3))

data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

The function np.random.permutation(n) generates a random permutation (shuffling) of numbers from 0 to n-1.

In [76]:
rw = np.random.permutation(4)
rw

array([3, 1, 0, 2], dtype=int32)

In [77]:
data.take(rw)

0   1   2
3  9  10  11
1  3   4   5
0  0   1   2
2  6   7   8

In [142]:
data.sample()

0   1   2
3  9  10  11

One hot Encoding

In [143]:
data = pd.DataFrame({
    "letter" : ["c", "a", "b", "b", "a"],
    "value" : [1,2,3,4,5]
})
data

letter  value
0      c      1
1      a      2
2      b      3
3      b      4
4      a      5

In [151]:
pd.get_dummies(data['letter']).astype(int)

a  b  c
0  0  0  1
1  1  0  0
2  0  1  0
3  0  1  0
4  1  0  0

In [156]:
df = pd.DataFrame({
    "letter" : list('ABCA'),
    "rank" : [1,2,3,4]
})
df

letter  rank
0      A     1
1      B     2
2      C     3
3      A     4

In [157]:
pd.get_dummies(df['letter']).astype(int)

A  B  C
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0